### ISSUE TITLE
Milestones

### ISSUE THREAD

**Issue by vvandermeersch** [vvandermeersch/synchrony#4]
- [x] Find journal and format requirements: Nature Plants/EcoEvo
- [x] Finalize one or two main figures (two is better) + supplementary figures
- [x] Write a first draft
- [x] Incorporate Jonathan and Dan suggestions
- [x] Pre-final version of manuscript (before last review by Lizzie)
- [x] First draft of cover letter
- [x] Submit!

**Comment by vvandermeersch** [comment]
**Short-form paper:**

- _Perspectives_ in Science: 
> highlight recent, exciting research and emerging themes that are of general interest but do not primarily discuss the author’s own work. With rare exceptions, **Perspectives should have no more than two authors**. Perspectives that comment on papers in Science (~**1000 words**, 15 references maximum, 1 figure) should add a new dimension to the research and not only describe what was done in the paper. There are also a variety of Perspectives that can “stand alone” (i.e., that are not connected to a paper in Science) and discuss emerging and important ideas in research. These can sometimes be opinionated or reflect on the history of a finding; they are usually peer-reviewed. Stand-alone Perspectives are ~**1800 words**, with 15 references maximum and 1 figure or table. Although **Perspectives are mostly invited**, we welcome inquiries regarding new advances and fresh insights

- _Perspectives_ in GCB (such as [Wolkovich et al. 2021](https://doi.org/10.1111/gcb.15746))
> a re-analysis, or challenge to prevailing views on a topical issue. While this category of article is designed to allow expression of viewpoints that may run counter to established viewpoints, articles must be anchored in sound reasoning developed from the peer-reviewed literature. The article must be sufficiently complete to convince reviewers of the value of the contribution. Articles that are essentially reviewing a topic, a statement of opinion not reasoned from the peer-reviewed literature, arguing for redirection of government funding for research and those primarily discussing the authors’ own work will not be considered. Perspective have only the following sections: body and references. Perspective articles should be no more than **1500 words** and have no more than no more than 1 table or figure total and 10 references

- _Correspondence_ or _Letters_ in New Phytologist
> pieces for our Forum section. All Forum pieces are subject to peer review, and are freely available to all readers upon publication. Forum pieces should focus on timely, research, comment and debate. The following article types are considered:
> - Correspondence. We encourage the exchange of ideas and open debate, and welcome such contributions to the Forum. Up to **1,500 words** is usual, with 1–2 figures/tables as appropriate. Please submit a presubmission enquiry, as above, if you wish to submit a correspondence piece.
> - Letters are our most free-ranging type of article, and we welcome short pieces that report novel research findings. Letters should typically be in the region of **1,500–2,000 words**, with 1–2 figures/tables. Materials and Methods should be provided as a separate section, and do not contribute to the word limits.

- _Brief Communication_ in Nature Plants/Nature Eco Evo
> reports a concise study of high quality and broad interest. Format:
-Brief unreferenced abstract – 3 sentences, up to 70 words.
-Title – up to 10 words (or 90 characters). 
-Main text – **1,000-1,500 words**, including abstract, references and figure legends, and contains no headings. 
-Display items – up to 2 items, although this may be flexible at the discretion of the editor, provided the page limit is observed. 
-Online Methods section should be included
-References – as a guideline, we typically recommend up to 20. Article titles are omitted from the reference list.
-Brief Communications should include received/accepted dates. 
-Brief Communications may be accompanied by supplementary information. 
-Brief Communications are peer reviewed.

- _Correspondence_ in Current Biology
> original research findings that have broad interest and can be presented concisely. These original research contributions will be subject to peer review. Correspondences should be written in a clear and accessible manner. They consist of a continuous main text without any sections or subheadings. Correspondence items do not have abstracts per se, but the first paragraph of the main text will be available in Medline. It should therefore comprise a short introduction as well as a brief summary of the most important conclusions. Correspondences must not exceed two pages of the printed journal. They should have no more than **1,000 words** of main text, a maximum of 10 references, and only one display item (one figure or table). Any nonessential details and experimental procedures can be described in an online-only Supplemental Information section, in which a maximum of two further display items can also be included.

- _Brief report_ in PNAS
> describe observations of immediate impact that may hold potential to initiate new avenues of research, provide compelling new data on controversies of broad interest and long-standing questions, or present a concise conceptual advance.
-All Brief Reports are published immediate open access​.
-Brief Reports are limited to 3 pages, which is approximately **1,600 words** (including the manuscript text, title page, abstract, and figure legends), and 15 references.
-Supporting information (SI) is limited to extended methods, essential supporting datasets, and videos (no additional tables or figures).
-All Brief Reports follow the Direct Submission mode of review and are not eligible as member-contributed submissions

@lizzieinvancouver Do you have anything in mind? (I included what we had written this summer)

**Comment by lizzieinvancouver** [comment]
@vvandermeersch I think Science may not want new analyses (in reading this) ... but the others sound like they would work. Do you have a preference? I think Nature Plants/Eco-evo/Current Biology is where I would start (in whatever order). 

FYI, I will be offline a good bit through 27 November so if I am not responding then that is the reason most likely!

**Comment by vvandermeersch** [comment]
@lizzieinvancouver I’m a bit unsure about Science, since I don't understand exactly what they mean by "_add a new dimension_" or "_fresh insights_". But otherwise, I don’t have a preference… maybe one of the two Nature journals?

**Comment by lizzieinvancouver** [comment]
@vvandermeersch Sure, starting with the two Nature journals sounds good to me.

**Comment by vvandermeersch** [comment]
@lizzieinvancouver I have finalized a first draft (still very much in the rough stage). We still have room: 870 words (out of 1000-1500 max) and about 10 references (20 max). Do you want to set a specific deadline before you review and make edits?

**Comment by lizzieinvancouver** [comment]
@vvandermeersch Nice work! I can take a look soon if you want (like, maybe this weekend, as I will bored during some travel -- if you sent it by 3pm PST on Friday) or is that too soon?

Also, before I forget -- one point I think we should make if possible is that there seem to be inherent correlations in climate in regions that the field does not fully understand/incorporate ... and we could cite this paper https://onlinelibrary.wiley.com/doi/full/10.1111/geb.13932 ... though I am sure we could find others to cite.

**Comment by vvandermeersch** [comment]
@lizzieinvancouver Unfortunately, I didn't write as much as I had hoped today (but spent some time trying to create a second figure), but I think you can still take a look. Sorry! I hope to find some time tomorrow.

Good point about the correlations. I also cited this one: https://besjournals.onlinelibrary.wiley.com/doi/full/10.1111/1365-2435.14329

**Comment by vvandermeersch** [comment]
@lizzieinvancouver By the way, you will find the draft here: https://github.com/vvandermeersch/synchrony/blob/main/docs/synchrony.tex (with the associated pdf in the same folder)

Have a nice week-end!

**Comment by vvandermeersch** [comment]
- [x] Incorporate Jonathan and Dan suggestions
- [x] Pre-final version of manuscript (before last review by Lizzie)
- [x] First draft of cover letter
- [x] Submit!

@lizzieinvancouver You will find both manuscript and cover letter in the repo! 

Edit: submitted today, Jan. 22

**Comment by vvandermeersch** [comment]
@lizzieinvancouver Revised manuscript for PNAS reviewers is here: https://github.com/vvandermeersch/synchrony/tree/main/docs/pnas/revision
I still need to write a longer abstract.
As well as a cover letter... But I've never done this for a revision!

**Comment by lizzieinvancouver** [comment]
> As well as a cover letter... But I've never done this for a revision!

I think you should do it! You can use it as a friendly reminder to the editor of the paper and the reviews.

**Comment by vvandermeersch** [comment]
@lizzieinvancouver I believe I incorporated all your changes! Thank you. I will read the full paper again, to be sure everything makes sense.

The only reviewer comment I did not yet treat:
> L17 - leaf unfolding of what?

I'm not sure what to add?!

I also wrote [a cover letter](https://github.com/vvandermeersch/synchrony/blob/main/docs/pnas/revision/coverletter_r1.pdf), quite short.

**Comment by lizzieinvancouver** [comment]
@vvandermeersch I think they want something like 'Leaf unfolding of temperate deciduous trees' or similar ...

I'll take a look at the cover letter when you have a draft of everything else.

**Comment by vvandermeersch** [comment]
@lizzieinvancouver I think you may take a look now! Thank you

**Comment by vvandermeersch** [comment]
@lizzieinvancouver Bonjour! I start working on a (short) waiver letter few days ago: 
https://github.com/vvandermeersch/synchrony/blob/main/docs/pnas/waiverletter.tex

I think it's still too short, I can add some facts on the paper?

**Comment by lizzieinvancouver** [comment]
@vvandermeersch I think it sounds good! 

It also makes me think the lab should start to keep notes on these requests.....

**Comment by vvandermeersch** [comment]
@lizzieinvancouver Since you asked me, quick summary of our paper journey:

Nature Plants (Brief Communication)
Nature Climate Change (Brief Communication)
Nature Ecology & Evolution (Brief Communication)
Current Biology (Report article +  presubmission inquiry)
PLOS Biology
PNAS (Brief Report)

Requirements for each journal are listed above

**Comment by lizzieinvancouver** [comment]
@vvandermeersch Thank you!
